<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SQ9BGJ7" failures="0" tests="6" name="TestCase.LoginPageTest" time="0.170" errors="1" timestamp="2022-07-20T09:13:22 PDT" skipped="5">
  <testcase classname="TestCase.LoginPageTest" name="setup" time="0.000">
    <skipped/>
  </testcase> <!-- setup -->
  <system-out/>
  <testcase classname="TestCase.LoginPageTest" name="beforSuit" time="0.170">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.base/java.io.File.<init>(File.java:278)
at com.relevantcodes.extentreports.Report.setFilePath(Report.java:527)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:80)
at com.relevantcodes.extentreports.ExtentReports.<init>(ExtentReports.java:420)
at TestCase.LoginPageTest.beforSuit(LoginPageTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforSuit -->
  <system-out/>
  <testcase classname="TestCase.LoginPageTest" name="validateLoginUrlTest" time="0.000">
    <skipped/>
  </testcase> <!-- validateLoginUrlTest -->
  <system-out/>
  <testcase classname="TestCase.LoginPageTest" name="logintitletest" time="0.000">
    <skipped/>
  </testcase> <!-- logintitletest -->
  <system-out/>
  <testcase classname="TestCase.LoginPageTest" name="loginWithBlankCredentialsTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginWithBlankCredentialsTest -->
  <system-out/>
  <testcase classname="TestCase.LoginPageTest" name="ddlogintest" time="0.000">
    <skipped/>
  </testcase> <!-- ddlogintest -->
  <system-out/>
</testsuite> <!-- TestCase.LoginPageTest -->
